# Generated by Django 2.2 on 2020-07-27 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_todo_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='description',
            new_name='descriptions',
        ),
    ]
